### ISSUE TITLE
WS network panel filter

### ISSUE THREAD

**Issue by janodvarko** [firebug/websocket-monitor#15]
In order to find new HTTP websockets upgrade requests, there should be a new filter.

Honza

**Comment by janodvarko** [comment]
See also #30 

Honza

**Comment by eliihen** [comment]
@janodvarko 

So I had a stab at this. I first tried to figure out if there was any way to hook in a custom filter function to `NetMonitorView.RequestsMenu`, but after trying for a while and looking through the source code of FF @ netmonitor-view.js, especially `get _filterPredicate`, it does not look like this is possible. Feel free to correct me if I am wrong.

Then i tried a different approach. And it works, kinda. In this approach I directly manipulate the DOM elements of netmonitor, setting hidden property if the filter is active and it is not a websocket request. You can have a look here: https://github.com/esphen/websocket-monitor/commit/52fe4a30dc821da4825a4490df63feb3df8adade. 

Not sure if I like my solution though, it feels kinda hacky to sidestep the netmonitor filters. Plus we may run into all kinds of ickyness because the two filters' logic are generally not aware of each other's state. What do you think? Any way to poke someone at Mozilla to see if it is possible to pass a custom filter function to `NetMonitorView.RequestsMenu`?

**Comment by janodvarko** [comment]
> Any way to poke someone at Mozilla to see if it is possible to pass a custom filter function to
> NetMonitorView.RequestsMenu?

Yes, I can do it. Please file a bug in bugzilla and attach your patch..

Honza

**Comment by eliihen** [comment]
@janodvarko I submitted a patch at https://bugzilla.mozilla.org/show_bug.cgi?id=1251767

I decided to simply implement the button and filter directly in network-monitor, as this seems to be the most sane approach. We can then decorate these requests as we have been doing, but leave the filtering up to the network monitor itself.

**Comment by janodvarko** [comment]
Excellent, I'll take a look at the Bugzilla bug and review it.

Honza

**Comment by eliihen** [comment]
This is now in FF proper, closing
