### ISSUE TITLE
Support for SockJS

### ISSUE THREAD

**Issue by janodvarko** [firebug/websocket-monitor#18]
We could have a support for SockJS protocol
https://github.com/sockjs

Honza

**Comment by janodvarko** [comment]
We can put the support into the add-on for now, but, we should learn and think about API we'll eventually offer for other protocols (add-ons).

It would be great to use the official parser NPM module from sockjs repo.

Honza

**Comment by fflorent** [comment]
@janodvarko What do you think?

If you want to test: 
- clone this repo: https://github.com/sockjs/sockjs-node.git
- in examples/echo, run : `npm install`
- apply the patch below in order to be able to close a connection (by entering `close` in the echo chat)
- run: `node server.js`
- open: http://localhost:9999

``` diff
diff --git a/examples/echo/server.js b/examples/echo/server.js
index af1d015..9339954 100644
--- a/examples/echo/server.js
+++ b/examples/echo/server.js
@@ -8,7 +8,11 @@ var sockjs_opts = {sockjs_url: "http://cdn.jsdelivr.net/sockjs/1.0.1/sockjs.min.
 var sockjs_echo = sockjs.createServer(sockjs_opts);
 sockjs_echo.on('connection', function(conn) {
     conn.on('data', function(message) {
-        conn.write(message);
+        if (message === 'close') {
+          conn.close(1000, 'foobar');
+        } else {
+          conn.write(message);
+        }
     });
 });
```

Resources:
- The code of the parsing: https://github.com/sockjs/sockjs-client/blob/0b4879d5e0b7f44d9f8accb28759fd965f70ea1f/lib/main.js#L237-L288
- The protocol documentation: https://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html

Florent

**Comment by fflorent** [comment]
> It would be great to use the official parser NPM module from sockjs repo.

NB: there is no parser NPM module... But the algorithm is quite simple.

Florent
